const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://telegra.ph/file/758549f0de2219884f387.jpg,https://telegra.ph/file/9498496b010dfb5900b80.jpg,https://telegra.ph/file/59bf80efbb6e6576b5a52.jpg,https://telegra.ph/file/ee0e191363161e88e4743.jpg" // ramadan Theme Images
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_16_26_05_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTA0LFxuICAgICAgICAxMzMsXG4gICAgICAgIDMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNzgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTIwLFxuICAgICAgICAyMDksXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNzYsXG4gICAgICAgIDMyLFxuICAgICAgICAxNTksXG4gICAgICAgIDE4LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTA4LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMSxcbiAgICAgICAgMzIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTg4LFxuICAgICAgICAyMzAsXG4gICAgICAgIDExMyxcbiAgICAgICAgODIsXG4gICAgICAgIDIwOSxcbiAgICAgICAgODhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjksXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTc4LFxuICAgICAgICAxMTksXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTcsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjQxLFxuICAgICAgICAxNDQsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyNDksXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjE1LFxuICAgICAgICAxNDUsXG4gICAgICAgIDg4LFxuICAgICAgICA0NyxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNDgsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjEyLFxuICAgICAgICAxNzksXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMzMsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjEsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTA1LFxuICAgICAgICA0OVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDExNSxcbiAgICAgICAgNTUsXG4gICAgICAgIDczLFxuICAgICAgICA4NCxcbiAgICAgICAgNTksXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjUsXG4gICAgICAgIDI0NCxcbiAgICAgICAgOTMsXG4gICAgICAgIDUyLFxuICAgICAgICA1NixcbiAgICAgICAgMTU4LFxuICAgICAgICAyMjQsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTIxLFxuICAgICAgICAxMzQsXG4gICAgICAgIDc3LFxuICAgICAgICA5OCxcbiAgICAgICAgMzAsXG4gICAgICAgIDE2NixcbiAgICAgICAgOTMsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNjksXG4gICAgICAgIDE5MixcbiAgICAgICAgMTQwLFxuICAgICAgICA5OSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMjEsXG4gICAgICAgIDU3LFxuICAgICAgICAxMDhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTExLFxuICAgICAgICAxNTksXG4gICAgICAgIDI1NCxcbiAgICAgICAgNDQsXG4gICAgICAgIDExNyxcbiAgICAgICAgOTksXG4gICAgICAgIDIxMCxcbiAgICAgICAgOTcsXG4gICAgICAgIDMxLFxuICAgICAgICAzOSxcbiAgICAgICAgNzksXG4gICAgICAgIDgwLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI1MCxcbiAgICAgICAgODMsXG4gICAgICAgIDEzOSxcbiAgICAgICAgNTYsXG4gICAgICAgIDE4NyxcbiAgICAgICAgODMsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTk4LFxuICAgICAgICA3OSxcbiAgICAgICAgMTQyLFxuICAgICAgICAxNTYsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMDdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU2LFxuICAgICAgICAyMjYsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMDAsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTAyLFxuICAgICAgICA5MixcbiAgICAgICAgNDEsXG4gICAgICAgIDU1LFxuICAgICAgICAyNDAsXG4gICAgICAgIDg5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMjM5LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE4LFxuICAgICAgICA3NCxcbiAgICAgICAgOTQsXG4gICAgICAgIDkwLFxuICAgICAgICAyNDYsXG4gICAgICAgIDU2LFxuICAgICAgICA4NCxcbiAgICAgICAgMTQwLFxuICAgICAgICAxODIsXG4gICAgICAgIDc4LFxuICAgICAgICA3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTA5LFxuICAgICAgICAyMyxcbiAgICAgICAgODgsXG4gICAgICAgIDExMixcbiAgICAgICAgMjAzLFxuICAgICAgICAyMDYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNjUsXG4gICAgICAgIDM4LFxuICAgICAgICA2LFxuICAgICAgICAxNzQsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNDIsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxLFxuICAgICAgICA5NCxcbiAgICAgICAgNzksXG4gICAgICAgIDIxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNjAsXG4gICAgICAgIDY2LFxuICAgICAgICAyMCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxODcsXG4gICAgICAgIDYxLFxuICAgICAgICAxNTQsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNzlcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDksXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgOTNcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgNixcbiAgICAgICAgICAyMCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNixcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICA4MVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwMixcbiAgICAgICAgMjI2LFxuICAgICAgICA0MCxcbiAgICAgICAgOTksXG4gICAgICAgIDkyLFxuICAgICAgICAxMjUsXG4gICAgICAgIDk5LFxuICAgICAgICAxNTIsXG4gICAgICAgIDYzLFxuICAgICAgICAxNCxcbiAgICAgICAgNjksXG4gICAgICAgIDcwLFxuICAgICAgICAxNTcsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTg5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDI3LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDY3LFxuICAgICAgICAyMzEsXG4gICAgICAgIDUsXG4gICAgICAgIDExNSxcbiAgICAgICAgMjUyLFxuICAgICAgICAyLFxuICAgICAgICAyMTAsXG4gICAgICAgIDEyMCxcbiAgICAgICAgODcsXG4gICAgICAgIDI2LFxuICAgICAgICAxMjgsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjM4LFxuICAgICAgICAyNyxcbiAgICAgICAgMTM4LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTA4LFxuICAgICAgICA3MSxcbiAgICAgICAgMjcsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTU5LFxuICAgICAgICAxNDIsXG4gICAgICAgIDc5LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjI3LFxuICAgICAgICA0NSxcbiAgICAgICAgMTg4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE0NixcbiAgICAgICAgNjEsXG4gICAgICAgIDUyLFxuICAgICAgICAxMTUsXG4gICAgICAgIDI1LFxuICAgICAgICAxOTksXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjAwLFxuICAgICAgICAxNDksXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDk5LFxuICBcImFkdlNlY3JldEtleVwiOiBcImF6K0ltV1pPZ2FycHlxQ2MrSFE0aHpWdFZ5VGZCVXhuVFBxaHRoZ3J3TmM9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTQ3MDc1MTQ2MjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjc0QzI2QjBEOUJBMDJDMkVGNzA4MUVERTM0RTBFODFDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkyNjM5NVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzA3NTE0NjIxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJFQ0RCQ0EwQkZCREJDMURFNUU1NTBDMEFGNTAyMjhDQ1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTQ5MjYzOTVcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiVlNfM2FVYXZTT2FuQk5sNW02bFpfd1wiLFxuICBcInBob25lSWRcIjogXCI4ZDk5NWNjNi1iNzRkLTQ4OTYtOGM5Yy02MGQyNTcwMjM1OGVcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTYyLFxuICAgICAgMTE3LFxuICAgICAgMTU1LFxuICAgICAgMTkyLFxuICAgICAgMjU1LFxuICAgICAgODUsXG4gICAgICA1LFxuICAgICAgMTg4LFxuICAgICAgMTk0LFxuICAgICAgMTg0LFxuICAgICAgOTIsXG4gICAgICAyNDUsXG4gICAgICAyMjQsXG4gICAgICA3OCxcbiAgICAgIDgwLFxuICAgICAgMTk1LFxuICAgICAgMTc1LFxuICAgICAgMTUxLFxuICAgICAgMTI5LFxuICAgICAgMjU0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAzMixcbiAgICAgIDIzMixcbiAgICAgIDk2LFxuICAgICAgMTMsXG4gICAgICAxNTEsXG4gICAgICAxNzgsXG4gICAgICAyMjUsXG4gICAgICAxNzUsXG4gICAgICAxNDcsXG4gICAgICAyNCxcbiAgICAgIDE2NyxcbiAgICAgIDMsXG4gICAgICAyMjIsXG4gICAgICAyNDQsXG4gICAgICA1MSxcbiAgICAgIDUwLFxuICAgICAgMjQsXG4gICAgICAxNzMsXG4gICAgICA3NCxcbiAgICAgIDE3MVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ05paHo1NENFTFRtM3JFR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiN1JwSTlYa2MralFHV2J5SHBRWVByMVllWk9ZSDJjNlU0WnE0Qko4YVFpbz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJtT2gyQWpOcmFQN0FlZUYrYTN6V0t4b0xlTFFXOWhobnAxcnRlbWg1NWlJZlZ0S0RNbHlOZ01BNlB6K0RYVEczM2FaWFBHZVdLU1UxdWd0MythZjdEUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJoNjIvbnIwQzR3Y0g5cUFvdU4ybHJXeFMrS2JIRVRNamd4bzJUeWdmdmJrMDErV1VmRzhRUXdraHhDYkpYQ0pmU3U2aFFDWUFDL1MrandEQTBDdW9DUT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjk0NzA3NTE0NjIxOjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjExMTc2MzkwNzQyNDI3Nzo2QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIkh5Z2ZcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjk0NzA3NTE0NjIxOjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgNixcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgNDJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcxNDkyNjM5MixcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUI2eVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQjZ5Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiRVBScUxxbHB1MzAwc0cxRVVSak1qak14R3Z3QVB0cnI0alpYMytNWW5Vbz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo2MDEwODQxMTYsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUI2ei5qc29uIjogIntcImtleURhdGFcIjpcIkNqeFU2alpNUEUvTjgwb3krcXZhMUNyRkR0ZCs1ejYxQTZWSHFNSWZXK289XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NjAxMDg0MTE5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzE0ODQyNDI5MTY3XCJ9Igp9" ;


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.1",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};

























global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
